"""create mandates and transaction_logs tables

Revision ID: 2f2b9d2f1e58
Revises: 
Create Date: 2026-07-08 15:06:34.600089

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2f2b9d2f1e58'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('mandates',
    sa.Column('mandate_id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.String(), nullable=False),
    sa.Column('agent_id', sa.String(), nullable=False),
    sa.Column('agent_platform', sa.String(), nullable=False),
    sa.Column('agent_display_name', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('max_amount_per_txn', sa.Numeric(), nullable=False),
    sa.Column('max_amount_per_window', sa.Numeric(), nullable=False),
    sa.Column('window_duration', sa.String(), nullable=False),
    sa.Column('max_amount_total', sa.Numeric(), nullable=False),
    sa.Column('merchant_allowlist', sa.JSON(), nullable=False),
    sa.Column('category_allowlist', sa.JSON(), nullable=False),
    sa.Column('allowed_time_window', sa.JSON(), nullable=False),
    sa.Column('original_intent_text', sa.Text(), nullable=False),
    sa.Column('user_facing_summary', sa.Text(), nullable=False),
    sa.PrimaryKeyConstraint('mandate_id')
    )
    op.create_index(op.f('ix_mandates_user_id'), 'mandates', ['user_id'], unique=False)
    op.create_table('transaction_logs',
    sa.Column('transaction_id', sa.UUID(), nullable=False),
    sa.Column('mandate_id', sa.UUID(), nullable=False),
    sa.Column('proposed_amount', sa.Numeric(), nullable=False),
    sa.Column('merchant_id', sa.String(), nullable=False),
    sa.Column('category', sa.String(), nullable=False),
    sa.Column('timestamp', sa.DateTime(timezone=True), nullable=False),
    sa.Column('source_content', sa.Text(), nullable=True),
    sa.Column('agent_reasoning', sa.Text(), nullable=True),
    sa.Column('decision', sa.String(), nullable=False),
    sa.Column('reason', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['mandate_id'], ['mandates.mandate_id'], ),
    sa.PrimaryKeyConstraint('transaction_id')
    )
    op.create_index(op.f('ix_transaction_logs_mandate_id'), 'transaction_logs', ['mandate_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_transaction_logs_mandate_id'), table_name='transaction_logs')
    op.drop_table('transaction_logs')
    op.drop_index(op.f('ix_mandates_user_id'), table_name='mandates')
    op.drop_table('mandates')
    # ### end Alembic commands ###
